/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.meetingai.controller; import cn.zhuatech.meetingai.common.ApiResponse; import cn.zhuatech.meetingai.service.MeetingActionService; import jakarta.validation.Valid; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; /**
                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                           */
@RestController @RequestMapping("/api/ai") @PreAuthorize("hasAnyRole('DOMAIN_USER','DOMAIN_OPERATOR','ADMIN')") public class AiFeatureController { private final MeetingActionService service; /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          */
public AiFeatureController(MeetingActionService service){this.service=service;} /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          */
@PostMapping("/meeting/analyze") public ApiResponse<MeetingActionService.Result> execute(@Valid @RequestBody MeetingActionService.Request request){return ApiResponse.ok("会议纪要与行动项分析完成",service.analyze(request));} }