/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.meetingai.controller;import cn.zhuatech.meetingai.common.ApiResponse;import cn.zhuatech.meetingai.service.MeetingMinutesPublicationService;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;/**
                                                                                                                                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                 */
@RestController @RequestMapping("/api/enterprise/meetingai")public class MeetingMinutesPublicationController{private final MeetingMinutesPublicationService service;/**
                                                                                                                                                                                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                     */
public MeetingMinutesPublicationController(MeetingMinutesPublicationService service){this.service=service;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */
@PostMapping("/minutes-publication")public ApiResponse<MeetingMinutesPublicationService.Assessment>assess(@Valid @RequestBody MeetingMinutesPublicationService.Request request){return ApiResponse.ok(service.assess(request));}}
