/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.meetingai.service;import org.junit.jupiter.api.Test;import static org.assertj.core.api.Assertions.assertThat;/**
                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                  */
class MeetingMinutesPublicationServiceTest{private final MeetingMinutesPublicationService s=new MeetingMinutesPublicationService();/**
                                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                     */
@Test void publishesApprovedMinutes(){var r=s.assess(new MeetingMinutesPublicationService.Request("M1",true,true,true,true,true,true,true,0,true,true,true));assertThat(r.decision()).isEqualTo(MeetingMinutesPublicationService.Decision.PUBLISH);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         */
@Test void reviewsRetentionAndAudit(){var r=s.assess(new MeetingMinutesPublicationService.Request("M2",true,true,true,true,true,true,true,0,false,false,true));assertThat(r.actions()).hasSize(2);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            */
@Test void blocksUnsafeMinutes(){var r=s.assess(new MeetingMinutesPublicationService.Request("M3",false,false,false,false,false,false,false,2,true,true,false));assertThat(r.blockers()).hasSize(9);}}
